---
-   hosts: OAISim-with-free5gc
    become: yes
    remote_user: root
    vars:
        BASE_DIR_INSTALL: 'oaisim-lte'

        num_ues_init_database: '100'
        web_application_access_port: '3000'
        init_free5gc_elements_simulation: 'false'
        start_webapp: 'true'
        deploy_oaisim: 'true'
        deploy_free5gc: 'true'
        docker_custom_subnet_network: '192.188.2.0/24'
        docker_custom_network_name: 'free5gc'
        ip_address_AMF: '192.188.2.2'
        ip_address_SMF: '192.188.2.3'
        ip_address_HSS: '192.188.2.4'
        ip_address_PCRF: '192.188.2.5'
        ip_address_UPF: '192.188.2.6'
        ip_address_MONGO_DB: '192.188.2.100'
        ip_address_WEB_UI: '192.188.2.101'
        ip_address_OAISIM_ENB: '192.188.2.253'
        ip_address_OAISIM_UE: '192.188.2.254'
        free5gc_st1_image_name: 'laboraufg/free5gc-st1'
        free5gc_webui_image_name: 'laboraufg/webui-free5gc'
        free5gc_mongodb_image_name: 'laboraufg/mongodb-free5gc'
        oaisim_enb_image_name: 'laboraufg/enb-openairsim'
        oaisim_ue_image_name: 'laboraufg/ue-openairsim'
        UE_container_name: 'ue'
        UE_folder_name_container_name: '/root/ue/'
        ENB_folder_name_container_name: '/root/enb/'
        ENB_container_name: 'enb'
        AMF_container_name: 'amf'
        SMF_container_name: 'smf'
        HSS_container_name: 'hss'
        PCRF_container_name: 'pcrf'
        UPF_container_name: 'upf'
        MONGO_DB_container_name: 'mongodb-svc'
        WEB_UI_container_name: 'webui'
        clear_file_instalation: 'true'
        HPLMN : "20893"
        default_username_WEBUI : "admin"
        default_password_WEBUI : "1423"
        enb_gumei_mcc_auth_param: '208'
        enb_gumei_mnc_auth_param: '93'
        log_level_tracer_free5gc: '5'
        path_workspace_free5gc: '/root/free5gc-stage-1'
        
        OPC : "e734f8734007d6c5ce7a0508809e7e9c"
        user_equiments:
            - { ue_id: UE0 ,   msin: '0000000001' }
            - { ue_id: UE1 ,   msin: '0000000002' }
            - { ue_id: UE2 ,   msin: '0000000003' }
            - { ue_id: UE3 ,   msin: '0000000004' }
            - { ue_id: UE4 ,   msin: '0000000005' }
            - { ue_id: UE5 ,   msin: '0000000006' }
            - { ue_id: UE6 ,   msin: '0000000007' }
            - { ue_id: UE7 ,   msin: '0000000008' }
            - { ue_id: UE8 ,   msin: '0000000009' }
            - { ue_id: UE9 ,   msin: '0000000010' }
            - { ue_id: UE10 ,  msin: '0000000011' }
            - { ue_id: UE11 ,  msin: '0000000012' }
            - { ue_id: UE12 ,  msin: '0000000013' }
            - { ue_id: UE13 ,  msin: '0000000014' }
            - { ue_id: UE14 ,  msin: '0000000015' }
            - { ue_id: UE15 ,  msin: '0000000016' }
            - { ue_id: UE16 ,  msin: '0000000017' }
            - { ue_id: UE17 ,  msin: '0000000018' }
            - { ue_id: UE18 ,  msin: '0000000019' }
            - { ue_id: UE19 ,  msin: '0000000020' }
            - { ue_id: UE20 ,  msin: '0000000021' }
            - { ue_id: UE21 ,  msin: '0000000022' }
            - { ue_id: UE22 ,  msin: '0000000023' }
            - { ue_id: UE23 ,  msin: '0000000024' }
            - { ue_id: UE24 ,  msin: '0000000025' }
            - { ue_id: UE25 ,  msin: '0000000026' }
            - { ue_id: UE26 ,  msin: '0000000027' }
            - { ue_id: UE27 ,  msin: '0000000028' }
            - { ue_id: UE28 ,  msin: '0000000029' }
            - { ue_id: UE29 ,  msin: '0000000030' }
            - { ue_id: UE30 ,  msin: '0000000031' }
            - { ue_id: UE31 ,  msin: '0000000032' }
            - { ue_id: UE32 ,  msin: '0000000033' }
            - { ue_id: UE33 ,  msin: '0000000034' }
            - { ue_id: UE34 ,  msin: '0000000035' }
            - { ue_id: UE35 ,  msin: '0000000036' }
            - { ue_id: UE36 ,  msin: '0000000037' }
            - { ue_id: UE37 ,  msin: '0000000038' }
            - { ue_id: UE38 ,  msin: '0000000039' }
            - { ue_id: UE39 ,  msin: '0000000040' }
            - { ue_id: UE40 ,  msin: '0000000041' }
            - { ue_id: UE41 ,  msin: '0000000042' }
            - { ue_id: UE42 ,  msin: '0000000043' }
            - { ue_id: UE43 ,  msin: '0000000044' }
            - { ue_id: UE44 ,  msin: '0000000045' }
            - { ue_id: UE45 ,  msin: '0000000046' }
            - { ue_id: UE46 ,  msin: '0000000047' }
            - { ue_id: UE47 ,  msin: '0000000048' }
            - { ue_id: UE48 ,  msin: '0000000049' }
            - { ue_id: UE49 ,  msin: '0000000050' }
            - { ue_id: UE50 ,  msin: '0000000051' }
            - { ue_id: UE51 ,  msin: '0000000052' }
            - { ue_id: UE52 ,  msin: '0000000053' }
            - { ue_id: UE53 ,  msin: '0000000054' }
            - { ue_id: UE54 ,  msin: '0000000055' }
            - { ue_id: UE55 ,  msin: '0000000056' }
            - { ue_id: UE56 ,  msin: '0000000057' }
            - { ue_id: UE57 ,  msin: '0000000058' }
            - { ue_id: UE58 ,  msin: '0000000059' }
            - { ue_id: UE59 ,  msin: '0000000060' }
            - { ue_id: UE60 ,  msin: '0000000061' }
            - { ue_id: UE61 ,  msin: '0000000062' }
            - { ue_id: UE62 ,  msin: '0000000063' }
            - { ue_id: UE63 ,  msin: '0000000064' }
            - { ue_id: UE64 ,  msin: '0000000065' }
            - { ue_id: UE65 ,  msin: '0000000066' }
            - { ue_id: UE66 ,  msin: '0000000067' }
            - { ue_id: UE67 ,  msin: '0000000068' }
            - { ue_id: UE68 ,  msin: '0000000069' }
            - { ue_id: UE69 ,  msin: '0000000070' }
            - { ue_id: UE70 ,  msin: '0000000071' }
            - { ue_id: UE71 ,  msin: '0000000072' }
            - { ue_id: UE72 ,  msin: '0000000073' }
            - { ue_id: UE73 ,  msin: '0000000074' }
            - { ue_id: UE74 ,  msin: '0000000075' }
            - { ue_id: UE75 ,  msin: '0000000076' }
            - { ue_id: UE76 ,  msin: '0000000077' }
            - { ue_id: UE77 ,  msin: '0000000078' }
            - { ue_id: UE78 ,  msin: '0000000079' }
            - { ue_id: UE79 ,  msin: '0000000080' }
            - { ue_id: UE80 ,  msin: '0000000081' }
            - { ue_id: UE81 ,  msin: '0000000082' }
            - { ue_id: UE82 ,  msin: '0000000083' }
            - { ue_id: UE83 ,  msin: '0000000084' }
            - { ue_id: UE84 ,  msin: '0000000085' }
            - { ue_id: UE85 ,  msin: '0000000086' }
            - { ue_id: UE86 ,  msin: '0000000087' }
            - { ue_id: UE87 ,  msin: '0000000088' }
            - { ue_id: UE88 ,  msin: '0000000089' }
            - { ue_id: UE89 ,  msin: '0000000090' }
            - { ue_id: UE90 ,  msin: '0000000091' }
            - { ue_id: UE91 ,  msin: '0000000092' }
            - { ue_id: UE92 ,  msin: '0000000093' }
            - { ue_id: UE93 ,  msin: '0000000094' }
            - { ue_id: UE94 ,  msin: '0000000095' }
            - { ue_id: UE95 ,  msin: '0000000096' }
            - { ue_id: UE96 ,  msin: '0000000097' }
            - { ue_id: UE97 ,  msin: '0000000098' }
            - { ue_id: UE98 ,  msin: '0000000099' }
            - { ue_id: UE99 ,   msin: '0000000100' }
            - { ue_id: UE100 ,  msin: '0000000101' }
            - { ue_id: UE101 ,  msin: '0000000102' }
            - { ue_id: UE102 ,  msin: '0000000103' }
            - { ue_id: UE103 ,  msin: '0000000104' }
            - { ue_id: UE104 ,  msin: '0000000105' }
            - { ue_id: UE105 ,  msin: '0000000106' }
            - { ue_id: UE106 ,  msin: '0000000107' }
            - { ue_id: UE107 ,  msin: '0000000108' }
            - { ue_id: UE108 ,  msin: '0000000109' }
            - { ue_id: UE109 ,  msin: '0000000110' }
            - { ue_id: UE110 ,  msin: '0000000111' }
            - { ue_id: UE111 ,  msin: '0000000112' }
            - { ue_id: UE112 ,  msin: '0000000112' }
            - { ue_id: UE113 ,  msin: '0000000114' }
            - { ue_id: UE114 ,  msin: '0000000115' }
            - { ue_id: UE115 ,  msin: '0000000116' }
            - { ue_id: UE116 ,  msin: '0000000117' }
            - { ue_id: UE117 ,  msin: '0000000118' }
            - { ue_id: UE118 ,  msin: '0000000119' }
            - { ue_id: UE119 ,  msin: '0000000120' }
            - { ue_id: UE120 ,  msin: '0000000121' }
            - { ue_id: UE121 ,  msin: '0000000122' }
            - { ue_id: UE122 ,  msin: '0000000123' }
            - { ue_id: UE123 ,  msin: '0000000124' }
            - { ue_id: UE124 ,  msin: '0000000125' }
            - { ue_id: UE125 ,  msin: '0000000126' }
            - { ue_id: UE126 ,  msin: '0000000127' }
            - { ue_id: UE127 ,  msin: '0000000128' }
            - { ue_id: UE128 ,  msin: '0000000129' }
            - { ue_id: UE129 ,  msin: '0000000130' }
            - { ue_id: UE130 ,  msin: '0000000131' }
            - { ue_id: UE131 ,  msin: '0000000132' }
            - { ue_id: UE132 ,  msin: '0000000133' }
            - { ue_id: UE133 ,  msin: '0000000134' }
            - { ue_id: UE134 ,  msin: '0000000135' }
            - { ue_id: UE135 ,  msin: '0000000136' }
            - { ue_id: UE136 ,  msin: '0000000137' }
            - { ue_id: UE137 ,  msin: '0000000138' }
            - { ue_id: UE138 ,  msin: '0000000139' }
            - { ue_id: UE139 ,  msin: '0000000140' }
            - { ue_id: UE140 ,  msin: '0000000141' }
            - { ue_id: UE141 ,  msin: '0000000142' }
            - { ue_id: UE142 ,  msin: '0000000143' }
            - { ue_id: UE143 ,  msin: '0000000144' }
            - { ue_id: UE144 ,  msin: '0000000145' }
            - { ue_id: UE145 ,  msin: '0000000146' }
            - { ue_id: UE146 ,  msin: '0000000147' }
            - { ue_id: UE147 ,  msin: '0000000148' }
            - { ue_id: UE148 ,  msin: '0000000149' }
            - { ue_id: UE149 ,  msin: '0000000150' }
            - { ue_id: UE150 ,  msin: '0000000151' }
            - { ue_id: UE151 ,  msin: '0000000152' }
            - { ue_id: UE152 ,  msin: '0000000153' }
            - { ue_id: UE153 ,  msin: '0000000154' }
            - { ue_id: UE154 ,  msin: '0000000155' }
            - { ue_id: UE155 ,  msin: '0000000156' }
            - { ue_id: UE156 ,  msin: '0000000157' }
            - { ue_id: UE157 ,  msin: '0000000158' }
            - { ue_id: UE158 ,  msin: '0000000159' }
            - { ue_id: UE159 ,  msin: '0000000160' }
            - { ue_id: UE160 ,  msin: '0000000161' }
            - { ue_id: UE161 ,  msin: '0000000162' }
            - { ue_id: UE162 ,  msin: '0000000163' }
            - { ue_id: UE163 ,  msin: '0000000164' }
            - { ue_id: UE164 ,  msin: '0000000165' }
            - { ue_id: UE165 ,  msin: '0000000166' }
            - { ue_id: UE166 ,  msin: '0000000167' }
            - { ue_id: UE167 ,  msin: '0000000168' }
            - { ue_id: UE168 ,  msin: '0000000169' }
            - { ue_id: UE169 ,  msin: '0000000170' }
            - { ue_id: UE170 ,  msin: '0000000171' }
            - { ue_id: UE171 ,  msin: '0000000172' }
            - { ue_id: UE172 ,  msin: '0000000173' }
            - { ue_id: UE173 ,  msin: '0000000174' }
            - { ue_id: UE174 ,  msin: '0000000175' }
            - { ue_id: UE175 ,  msin: '0000000176' }
            - { ue_id: UE176 ,  msin: '0000000177' }
            - { ue_id: UE177 ,  msin: '0000000178' }
            - { ue_id: UE178 ,  msin: '0000000179' }
            - { ue_id: UE179 ,  msin: '0000000180' }
            - { ue_id: UE180 ,  msin: '0000000181' }
            - { ue_id: UE181 ,  msin: '0000000182' }
            - { ue_id: UE182 ,  msin: '0000000183' }
            - { ue_id: UE183 ,  msin: '0000000184' }
            - { ue_id: UE184 ,  msin: '0000000185' }
            - { ue_id: UE185 ,  msin: '0000000186' }
            - { ue_id: UE186 ,  msin: '0000000187' }
            - { ue_id: UE187 ,  msin: '0000000188' }
            - { ue_id: UE188 ,  msin: '0000000189' }
            - { ue_id: UE189 ,  msin: '0000000190' }
            - { ue_id: UE190 ,  msin: '0000000191' }
            - { ue_id: UE191 ,  msin: '0000000192' }
            - { ue_id: UE192 ,  msin: '0000000193' }
            - { ue_id: UE193 ,  msin: '0000000194' }
            - { ue_id: UE194 ,  msin: '0000000195' }
            - { ue_id: UE195 ,  msin: '0000000196' }
            - { ue_id: UE196 ,  msin: '0000000197' }
            - { ue_id: UE197 ,  msin: '0000000198' }
            - { ue_id: UE198 ,  msin: '0000000199' }
            - { ue_id: UE199 ,  msin: '0000000200' }
    tasks:
        - name: Environment validation!
          assert:
            that:
              - ansible_memtotal_mb >= 1024
            msg: "Minimum memory requirements in the deployment environment is 4GB! Operation failed!"

        - name : Git clone openair-cn 
          shell: git clone https://gitlab.eurecom.fr/oai/openair-cn.git
          args:
              chdir: "{{ BASE_DIR_INSTALL }}"